### ISSUE TITLE
webview_flutter2.0.4相冲突

### ISSUE THREAD

**Issue by WANGNlMA** [c1avie/TRTCSimpleDemo#12]
The following _CastError was thrown building FutureBuilder<WebViewController>(dirty, state:
_FutureBuilderState<WebViewController>#5d67a):
Null check operator used on a null value

The relevant error-causing widget was:
  FutureBuilder<WebViewController> file:///D:/02B-flutter/flutter_to_uni/lib/main.dart:299:12

When the exception was thrown, this was the stack:
#0      NavigationControls.build.<anonymous closure> (package:flutter_to_uni/main.dart:305:59)
#1      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:773:55)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4474:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4658:11)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4469:5)
...     Normal element mounting (7 frames)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
#16     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6094:32)
...     Normal element mounting (19 frames)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
#36     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6094:32)
...     Normal element mounting (129 frames)
#165    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
#166    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6094:32)
...     Normal element mounting (238 frames)
#404    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
#405    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6094:32)
...     Normal element mounting (309 frames)
#714    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
#715    Element.updateChild (package:flutter/src/widgets/framework.dart:3306:18)
#716    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1182:16)
#717    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1153:5)
#718    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1095:18)
#719    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2647:19)
#720    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1094:13)
#721    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:9

**Comment by c1avie** [comment]
视频view跟webview同一个页面展示了吗

**Comment by WANGNlMA** [comment]
没有在同一界面，我将webview 更换为flutter_inappwebview就没问题了
