### ISSUE TITLE
ios这边预览摄像头画面的时候还要先stopLocalPreview之后，再次startLocalPreview才能渲染摄像头画面

### ISSUE THREAD

**Issue by lan2000** [c1avie/TRTCSimpleDemo#13]
IOS预览摄像头画面的时候还要先stopLocalPreview之后，再次startLocalPreview才能渲染摄像头画面。这样就其他用户就会看到当前用户画面闪一下的现象。

比如demo里面的用户A，双击自己的摄像头预览画面进行全屏，用户B看得A的画面就会闪一下

![image](https://user-images.githubusercontent.com/29618907/119292760-974bd880-bc83-11eb-8e31-81f480bd5196.png)

**Comment by lan2000** [comment]
stopLocalPreview-》setState-》TRTCCloudVideoView-onViewCreated-》startLocalPreview

**Comment by c1avie** [comment]
这里我们定位下，有结论了同步

**Comment by lan2000** [comment]
> 这里我们定位下，有结论了同步

txDeviceManager.setAudioRoute(
                          TRTCCloudDef.TRTC_AUDIO_ROUTE_EARPIECE);

跑的demo，设置听筒模式大多时候不起作用，偶尔又能起作用，测试机型：荣耀v10，安卓10

**Comment by lan2000** [comment]
还是这个demo，多个人进行测试直播，8个人进入直播凑成俩页，左右快速滑动进行切换分页，过一会儿手机直接“吧”的一声（扬声器），手机直接重启了。测试机型：荣耀v10，安卓10

打印的信息：

E/MethodChannel#flutter/platform_views( 2895): Failed to handle method call
E/MethodChannel#flutter/platform_views( 2895): java.lang.RuntimeException: InputChannel is not initialized.
E/MethodChannel#flutter/platform_views( 2895): 	at android.view.InputEventReceiver.nativeInit(Native Method)
E/MethodChannel#flutter/platform_views( 2895): 	at android.view.InputEventReceiver.<init>(InputEventReceiver.java:89)
E/MethodChannel#flutter/platform_views( 2895): 	at android.view.ViewRootImpl$WindowInputEventReceiver.<init>(ViewRootImpl.java:8109)
E/MethodChannel#flutter/platform_views( 2895): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1049)
E/MethodChannel#flutter/platform_views( 2895): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:428)
E/MethodChannel#flutter/platform_views( 2895): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:118)
E/MethodChannel#flutter/platform_views( 2895): 	at android.app.Dialog.show(Dialog.java:448)
E/MethodChannel#flutter/platform_views( 2895): 	at android.app.Presentation.show(Presentation.java:250)
E/MethodChannel#flutter/platform_views( 2895): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/MethodChannel#flutter/platform_views( 2895): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/MethodChannel#flutter/platform_views( 2895): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/MethodChannel#flutter/platform_views( 2895): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/MethodChannel#flutter/platform_views( 2895): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/MethodChannel#flutter/platform_views( 2895): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/platform_views( 2895): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/platform_views( 2895): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#flutter/platform_views( 2895): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views( 2895): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/MethodChannel#flutter/platform_views( 2895): 	at android.os.Looper.loop(Looper.java:173)
E/MethodChannel#flutter/platform_views( 2895): 	at android.app.ActivityThread.main(ActivityThread.java:8178)
E/MethodChannel#flutter/platform_views( 2895): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views( 2895): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/MethodChannel#flutter/platform_views( 2895): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
I/Choreographer( 2895): Skipped 43 frames!  The application may be doing too much work on its main thread.
I/HiTouch_HiTouchSensor( 2895): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector( 2895): onAttached, package=com.tencent.trtc_demo, windowType=2030, mHiTouchRestricted=true
D/mali_winsys( 2895): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
E/flutter ( 2895): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, InputChannel is not initialized., null, java.lang.RuntimeException: InputChannel is not initialized.
E/flutter ( 2895): 	at android.view.InputEventReceiver.nativeInit(Native Method)
E/flutter ( 2895): 	at android.view.InputEventReceiver.<init>(InputEventReceiver.java:89)
E/flutter ( 2895): 	at android.view.ViewRootImpl$WindowInputEventReceiver.<init>(ViewRootImpl.java:8109)
E/flutter ( 2895): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1049)
E/flutter ( 2895): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:428)
E/flutter ( 2895): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:118)
E/flutter ( 2895): 	at android.app.Dialog.show(Dialog.java:448)
E/flutter ( 2895): 	at android.app.Presentation.show(Presentation.java:250)
E/flutter ( 2895): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/flutter ( 2895): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/flutter ( 2895): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/flutter ( 2895): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/flutter ( 2895): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter ( 2895): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 2895): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 2895): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter ( 2895): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 2895): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/flutter ( 2895): 	at android.os.Looper.loop(Looper.java:173)
E/flutter ( 2895): 	at android.app.ActivityThread.main(ActivityThread.java:8178)
E/flutter ( 2895): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 2895): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/flutter ( 2895): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/flutter ( 2895): )
E/flutter ( 2895): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter ( 2895): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter ( 2895): <asynchronous suspension>
E/flutter ( 2895): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 2895): #3      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1039:54)
E/flutter ( 2895): #4      AndroidViewController.create (package:flutter/src/services/platform_views.dart:749:11)
E/flutter ( 2895): #5      TextureAndroidViewController.create (package:flutter/src/services/platform_views.dart:1018:34)
E/flutter ( 2895): #6      TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1002:14)
E/flutter ( 2895): #7      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter ( 2895): #8      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter ( 2895): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1756:9)
E/flutter ( 2895): #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter ( 2895): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter ( 2895): #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter ( 2895): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter ( 2895): #14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter ( 2895): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter ( 2895): #16     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:560:15)
E/flutter ( 2895): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter ( 2895): #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter ( 2895): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter ( 2895): #20     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:268:14)
E/flutter ( 2895): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter ( 2895): #22     _RenderLayoutBuilder.perfo
E/SurfaceComposerClient( 2895): SurfaceComposerClient::createSurface error Out of memory
E/SurfaceView( 2895): Exception configuring surface
E/SurfaceView( 2895): android.view.Surface$OutOfResourcesException
E/SurfaceView( 2895): 	at android.view.SurfaceControl.nativeCreate(Native Method)
E/SurfaceView( 2895): 	at android.view.SurfaceControl.<init>(SurfaceControl.java:895)
E/SurfaceView( 2895): 	at android.view.SurfaceControl.<init>(SurfaceControl.java:97)
E/SurfaceView( 2895): 	at android.view.SurfaceControl$Builder.build(SurfaceControl.java:614)
E/SurfaceView( 2895): 	at android.view.ViewRootImpl.createBoundsSurface(ViewRootImpl.java:1697)
E/SurfaceView( 2895): 	at android.view.SurfaceView.updateSurface(SurfaceView.java:615)
E/SurfaceView( 2895): 	at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:162)
E/SurfaceView( 2895): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
E/SurfaceView( 2895): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2944)
E/SurfaceView( 2895): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1857)
E/SurfaceView( 2895): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8089)
E/SurfaceView( 2895): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
E/SurfaceView( 2895): 	at android.view.Choreographer.doCallbacks(Choreographer.java:875)
E/SurfaceView( 2895): 	at android.view.Choreographer.doFrame(Choreographer.java:776)
E/SurfaceView( 2895): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
E/SurfaceView( 2895): 	at android.os.Handler.handleCallback(Handler.java:888)
E/SurfaceView( 2895): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/SurfaceView( 2895): 	at android.os.Looper.loop(Looper.java:213)
E/SurfaceView( 2895): 	at android.app.ActivityThread.main(ActivityThread.java:8178)
E/SurfaceView( 2895): 	at java.lang.reflect.Method.invoke(Native Method)
E/SurfaceView( 2895): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/SurfaceView( 2895): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
I/OpenGLRenderer( 2895): Davey! duration=803ms; Flags=1, IntendedVsync=1302260216467417, Vsync=1302260933134055, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1302260945344515, AnimationStart=1302260945429410, PerformTraversalsStart=1302260946654410, DrawStart=1302261005679410, SyncQueued=1302261006344515, SyncStart=1302261006862223, IssueDrawCommandsStart=1302261007015348, SwapBuffers=1302261019302848, FrameCompleted=1302261020703890, DequeueBufferDuration=9180000, QueueBufferDuration=1041000, 
I/HiTouch_HiTouchSensor( 2895): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector( 2895): onAttached, package=com.tencent.trtc_demo, windowType=2030, mHiTouchRestricted=true

**Comment by lan2000** [comment]
一开始以为是startRemoteView或者startLocalPreview导致，后来屏蔽掉startLocalPreview和startRemoteView之后进行测试，任然有这个问题。
![image](https://user-images.githubusercontent.com/29618907/120070799-daaca980-c0be-11eb-92ad-a79a5645a20e.png)


E/MethodChannel#flutter/platform_views(11950): Failed to handle method call
E/MethodChannel#flutter/platform_views(11950): java.lang.RuntimeException: InputChannel is not initialized.
E/MethodChannel#flutter/platform_views(11950): 	at android.view.InputEventReceiver.nativeInit(Native Method)
E/MethodChannel#flutter/platform_views(11950): 	at android.view.InputEventReceiver.<init>(InputEventReceiver.java:89)
E/MethodChannel#flutter/platform_views(11950): 	at android.view.ViewRootImpl$WindowInputEventReceiver.<init>(ViewRootImpl.java:8109)
E/MethodChannel#flutter/platform_views(11950): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1049)
E/MethodChannel#flutter/platform_views(11950): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:428)
E/MethodChannel#flutter/platform_views(11950): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:118)
E/MethodChannel#flutter/platform_views(11950): 	at android.app.Dialog.show(Dialog.java:448)
E/MethodChannel#flutter/platform_views(11950): 	at android.app.Presentation.show(Presentation.java:250)
E/MethodChannel#flutter/platform_views(11950): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/MethodChannel#flutter/platform_views(11950): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/MethodChannel#flutter/platform_views(11950): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/MethodChannel#flutter/platform_views(11950): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/MethodChannel#flutter/platform_views(11950): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/MethodChannel#flutter/platform_views(11950): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/platform_views(11950): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/platform_views(11950): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#flutter/platform_views(11950): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(11950): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/MethodChannel#flutter/platform_views(11950): 	at android.os.Looper.loop(Looper.java:173)
E/MethodChannel#flutter/platform_views(11950): 	at android.app.ActivityThread.main(ActivityThread.java:8178)
E/MethodChannel#flutter/platform_views(11950): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(11950): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/MethodChannel#flutter/platform_views(11950): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/flutter (11950): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, InputChannel is not initialized., null, java.lang.RuntimeException: InputChannel is not initialized.
E/flutter (11950): 	at android.view.InputEventReceiver.nativeInit(Native Method)
E/flutter (11950): 	at android.view.InputEventReceiver.<init>(InputEventReceiver.java:89)
E/flutter (11950): 	at android.view.ViewRootImpl$WindowInputEventReceiver.<init>(ViewRootImpl.java:8109)
E/flutter (11950): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1049)
E/flutter (11950): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:428)
E/flutter (11950): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:118)
E/flutter (11950): 	at android.app.Dialog.show(Dialog.java:448)
E/flutter (11950): 	at android.app.Presentation.show(Presentation.java:250)
E/flutter (11950): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/flutter (11950): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/flutter (11950): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/flutter (11950): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/flutter (11950): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter (11950): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (11950): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (11950): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (11950): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (11950): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/flutter (11950): 	at android.os.Looper.loop(Looper.java:173)
E/flutter (11950): 	at android.app.ActivityThread.main(ActivityThread.java:8178)
E/flutter (11950): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (11950): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/flutter (11950): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/flutter (11950): )
E/flutter (11950): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (11950): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (11950): <asynchronous suspension>
E/flutter (11950): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (11950): #3      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1039:54)
E/flutter (11950): #4      AndroidViewController.create (package:flutter/src/services/platform_views.dart:749:11)
E/flutter (11950): #5      TextureAndroidViewController.create (package:flutter/src/services/platform_views.dart:1018:34)
E/flutter (11950): #6      TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1002:14)
E/flutter (11950): #7      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (11950): #8      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (11950): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1756:9)
E/flutter (11950): #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (11950): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (11950): #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (11950): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (11950): #14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (11950): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (11950): #16     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:560:15)
E/flutter (11950): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (11950): #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (11950): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (11950): #20     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:268:14)
E/flutter (11950): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (11950): #22     _RenderLayoutBuilder.perfo
E/MethodChannel#flutter/platform_views(11950): Failed to handle method call
E/MethodChannel#flutter/platform_views(11950): java.lang.RuntimeException: InputChannel is not initialized.
E/MethodChannel#flutter/platform_views(11950): 	at android.view.InputEventReceiver.nativeInit(Native Method)
E/MethodChannel#flutter/platform_views(11950): 	at android.view.InputEventReceiver.<init>(InputEventReceiver.java:89)
E/MethodChannel#flutter/platform_views(11950): 	at android.view.ViewRootImpl$WindowInputEventReceiver.<init>(ViewRootImpl.java:8109)
E/MethodChannel#flutter/platform_views(11950): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1049)
E/MethodChannel#flutter/platform_views(11950): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:428)
E/MethodChannel#flutter/platform_views(11950): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:118)
E/MethodChannel#flutter/platform_views(11950): 	at android.app.Dialog.show(Dialog.java:448)
E/MethodChannel#flutter/platform_views(11950): 	at android.app.Presentation.show(Presentation.java:250)
E/MethodChannel#flutter/platform_views(11950): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/MethodChannel#flutter/platform_views(11950): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/MethodChannel#flutter/platform_views(11950): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/MethodChannel#flutter/platform_views(11950): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/MethodChannel#flutter/platform_views(11950): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/MethodChannel#flutter/platform_views(11950): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/platform_views(11950): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/platform_views(11950): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#flutter/platform_views(11950): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(11950): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/MethodChannel#flutter/platform_views(11950): 	at android.os.Looper.loop(Looper.java:173)
E/MethodChannel#flutter/platform_views(11950): 	at android.app.ActivityThread.main(ActivityThread.java:8178)
E/MethodChannel#flutter/platform_views(11950): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(11950): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/MethodChannel#flutter/platform_views(11950): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/flutter (11950): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, InputChannel is not initialized., null, java.lang.RuntimeException: InputChannel is not initialized.
E/flutter (11950): 	at android.view.InputEventReceiver.nativeInit(Native Method)
E/flutter (11950): 	at android.view.InputEventReceiver.<init>(InputEventReceiver.java:89)
E/flutter (11950): 	at android.view.ViewRootImpl$WindowInputEventReceiver.<init>(ViewRootImpl.java:8109)
E/flutter (11950): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1049)
E/flutter (11950): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:428)
E/flutter (11950): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:118)
E/flutter (11950): 	at android.app.Dialog.show(Dialog.java:448)
E/flutter (11950): 	at android.app.Presentation.show(Presentation.java:250)
E/flutter (11950): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/flutter (11950): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/flutter (11950): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/flutter (11950): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/flutter (11950): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter (11950): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (11950): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (11950): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (11950): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (11950): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/flutter (11950): 	at android.os.Looper.loop(Looper.java:173)
E/flutter (11950): 	at android.app.ActivityThread.main(ActivityThread.java:8178)
E/flutter (11950): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (11950): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/flutter (11950): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/flutter (11950): )
E/flutter (11950): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (11950): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (11950): <asynchronous suspension>
E/flutter (11950): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (11950): #3      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1039:54)
E/flutter (11950): #4      AndroidViewController.create (package:flutter/src/services/platform_views.dart:749:11)
E/flutter (11950): #5      TextureAndroidViewController.create (package:flutter/src/services/platform_views.dart:1018:34)
E/flutter (11950): #6      TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1002:14)
E/flutter (11950): #7      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (11950): #8      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (11950): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1756:9)
E/flutter (11950): #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (11950): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (11950): #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (11950): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (11950): #14     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (11950): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (11950): #16     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:560:15)
E/flutter (11950): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (11950): #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (11950): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (11950): #20     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:268:14)
E/flutter (11950): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (11950): #22     _RenderLayoutBuilder.perfo
I/HiTouch_HiTouchSensor(11950): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector(11950): onAttached, package=com.tencent.trtc_demo, windowType=2030, mHiTouchRestricted=true
Lost connection to device.

**Comment by c1avie** [comment]
方便录个屏发来看看是什么现象吗

**Comment by c1avie** [comment]
手机可能不支持同时渲染8个视频画面，试试5个视频画面还有问题吗

**Comment by lan2000** [comment]
> 手机可能不支持同时渲染8个视频画面，试试5个视频画面还有问题吗

本机录屏不了，系统直接重启了，保存不了。
5个视频画面我刚才也试过了，还是会出现

**Comment by lan2000** [comment]
> 手机可能不支持同时渲染8个视频画面，试试5个视频画面还有问题吗

我qq联系你，发给你视频

**Comment by lan2000** [comment]
> 手机可能不支持同时渲染8个视频画面，试试5个视频画面还有问题吗

你好，我已经通过qq发给你了

**Comment by lan2000** [comment]
sdk不是新增俩接口：
trtcCloud.updateRemoteView(viewId, streamType, userId)
trtcCloud.updateLocalView(viewId)

这俩接口是否是解决上面ios渲染的问题。
是的话demo里面怎么没用更新

**Comment by gdwenjun** [comment]
> sdk不是新增俩接口：
> trtcCloud.updateRemoteView(viewId, streamType, userId)
> trtcCloud.updateLocalView(viewId)
> 
> 这俩接口是否是解决上面ios渲染的问题。
> 是的话demo里面怎么没用更新

可以解决，本地视频如果viewId有变化的时候，有两种办法j解决视频渲染的问题，一个是先stop后startLocalPreview，该方法有缺陷是远端视频会先停顿一下后才正常。另一种方法是用updateLocalView直接更新到新的viewID上面，建议使用updateLocalView。
可以参考一对一视频通话，双击切换大小画面就用到了
[ updateLocalView 和 updateRemoteView](https://github.com/tencentyun/TRTCFlutterScenesDemo/blob/main/lib/TRTCCallingDemo/ui/VideoCall/TRTCCallingVideo.dart)

**Comment by gdwenjun** [comment]
可以解决，本地视频如果viewId有变化的时候，有两种办法j解决视频渲染的问题，一个是先stop后startLocalPreview，该方法有缺陷是远端视频会先停顿一下后才正常。另一种方法是用updateLocalView直接更新到新的viewID上面，建议使用updateLocalView。
可以参考一对一视频通话，双击切换大小画面就用到了
updateLocalView 和 updateRemoteView
