### ISSUE TITLE
flutter2.2.1闪退...

### ISSUE THREAD

**Issue by elinxer** [c1avie/TRTCSimpleDemo#15]
flutter2.2.1闪退...

**Comment by elinxer** [comment]
Exception attempting to connect to the VM Service: SocketException: OS Error: 远程计算机拒绝网络连接。
, errno = 1225, address = 127.0.0.1, port = 64791
This was attempt #5150. Will retry in 0:00:01.600000.
E/AndroidRuntime(14512): FATAL EXCEPTION: main
E/AndroidRuntime(14512): Process: com.tencent.trtc_demo, PID: 14512
E/AndroidRuntime(14512): java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.tencent.liteav.basic.util.TXCCommonUtil.nativeGetSDKVersion() (tried Java_com_tencent_liteav_basic_util_TXCCommonUtil_nativeGetSDKVersion and Java_com_tencent_liteav_basic_util_TXCCommonUtil_nativeGetSDKVersion__)
E/AndroidRuntime(14512): 	at com.tencent.liteav.basic.util.TXCCommonUtil.nativeGetSDKVersion(Native Method)
E/AndroidRuntime(14512): 	at com.tencent.liteav.basic.util.TXCCommonUtil.getSDKVersion(TXCCommonUtil.java:41)
E/AndroidRuntime(14512): 	at com.tencent.liteav.trtc.impl.TRTCCloudImpl.init(TRTCCloudImpl.java:501)
E/AndroidRuntime(14512): 	at com.tencent.liteav.trtc.impl.TRTCCloudImpl.<init>(TRTCCloudImpl.java:394)
E/AndroidRuntime(14512): 	at com.tencent.liteav.trtc.impl.TRTCCloudImpl.sharedInstance(TRTCCloudImpl.java:376)
E/AndroidRuntime(14512): 	at com.tencent.trtc.TRTCCloud.sharedInstance(TRTCCloud.java:41)
E/AndroidRuntime(14512): 	at com.tencent.trtcplugin.view.TRTCCloudVideoPlatformView.<init>(TRTCCloudVideoPlatformView.java:40)
E/AndroidRuntime(14512): 	at com.tencent.trtcplugin.TRTCCloudPlugin.<init>(TRTCCloudPlugin.java:82)
E/AndroidRuntime(14512): 	at com.tencent.trtcplugin.TRTCCloudPlugin.onAttachedToEngine(TRTCCloudPlugin.java:102)
E/AndroidRuntime(14512): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:143)
E/AndroidRuntime(14512): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:19)
E/AndroidRuntime(14512): 	at com.tencent.trtc_demo.MainActivity.configureFlutterEngine(MainActivity.java:11)
E/AndroidRuntime(14512): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
E/AndroidRuntime(14512): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:409)
E/AndroidRuntime(14512): 	at android.app.Activity.performCreate(Activity.java:8000)
E/AndroidRuntime(14512): 	at android.app.Activity.performCreate(Activity.java:7984)
E/AndroidRuntime(14512): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/AndroidRuntime(14512): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/AndroidRuntime(14512): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(14512): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(14512): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(14512): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(14512): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(14512): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(14512): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(14512): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(14512): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14512): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(14512): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by elinxer** [comment]
示例1：
【Android】-【4.2.1】win 打包安装直接闪退，没有成功打开APP
【当前现象】：win 打包安装直接闪退，没有成功打开APP
【问题时间段】：2021-05-30
【机型】：安卓studio模拟器 pix xl
【之前版本有无此问题】：未尝试
【是否必现】：必现
【复现方法】：flutter+Android studio最新版本
【日志或者描述、截图】：安装时闪退

**Comment by c1avie** [comment]
建议使用真机调试，安卓不支持模拟器的。
