### ISSUE TITLE
【Android/iOS】-【1.0.5】語音沙龍只剩兩位主播時, 當一位主播下麥或離開房間, 房主的AudioStream也會被停止

### ISSUE THREAD

**Issue by rest950** [c1avie/TRTCSimpleDemo#19]
【当前现象】：語音沙龍只剩兩位主播時, 當一位主播下麥或離開房間, 房主的AudioStream也會被停止
【SDKAppID】：1400529354
【房间号】: 345618262
【useID】：0001
【问题时间段】：2021-06-09 1530:~16:00
【机型】：PIXEL 3 XL  /  Redmi Note 5 /  IPhone11 (Simulator)
【之前版本有无此问题】：目前試過trtc_cloud 1.0.3 - 1.0.5 皆有此問題
【是否必现】：必現
【复现方法】：房主A創建語音沙龍 -> userB進入 -> userB申請上麥成功 -> userB下麥 or 直接離開房間 -> 房主A AudioStream失效

【描述】使用範例FlutterDemo時發現, 語音沙龍只剩兩位主播(一位房主A、一位主播B)時, 當主播B下麥或離開房間, 房主A的AudioStream被停止, 此時有新的user入房也聽不到房主的Stream

【日志】有發現Stream被Remove及Audio Device被Release的情況, 完整日誌如下
[房主裝置Stream失效當下Log.txt](https://github.com/c1avie/TRTCSimpleDemo/files/6622132/Stream.Log.txt)

**Comment by c1avie** [comment]
是用的我们语音沙龙的demo还是自己开发的？

**Comment by rest950** [comment]
是用语音沙龙的demo

**Comment by c1avie** [comment]
我们排查一下，有结果再反馈

**Comment by c1avie** [comment]
问题找到了，是/bse/DemoSevice里面注册了一个全局的语音通话场景信令。如果你只是需要语音沙龙场景的话，可以把这里的事件监听去掉，TRTCCallingDemo整个目录也可以去掉。

**Comment by rest950** [comment]
了解，問題解決了，非常感謝協助！
