### ISSUE TITLE
会考虑支持TXLiteAVSDK_Professional吗？

### ISSUE THREAD

**Issue by xx-li** [c1avie/TRTCSimpleDemo#20]
您好，项目现在是基于`TXLiteAVSDK_TRTC`SDK开发的，后续会考虑支持`TXLiteAVSDK_Professional`吗？

**Comment by c1avie** [comment]
你们有用到除了TRTC的什么能力？

**Comment by xx-li** [comment]
我们是做的音频直播，有连麦功能，用`TXLivePlayer`进行拉流，用`TXLivePush`进行推流。

**Comment by xx-li** [comment]
我对Android部分不太熟悉，如果有同学愿意做安卓端的工作，我可以开发iOS和Dart端对这两个类的支持

**Comment by c1avie** [comment]
TXLive直播这块是另外团队负责的，暂时没有计划封装。TRTC也可以用来做直播，可参考：
https://cloud.tencent.com/document/product/647/57389
