### ISSUE TITLE
snapshotVideo 报错Error Domain=NSCocoaErrorDomain Code=513 "您没有将文件“path”存储到文件夹“System@snap-3904184”中的权限。" UserInfo={NSFilePath=/path, NSUnderlyingError=0x2839cd4d0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}

### ISSUE THREAD

**Issue by chenchen0206** [c1avie/TRTCSimpleDemo#23]
我在使用snapshotVideo Error Domain=NSCocoaErrorDomain Code=513 "您没有将文件“path”存储到文件夹“System@snap-3904184”中的权限。" UserInfo={NSFilePath=/path, NSUnderlyingError=0x2839cd4d0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
这个是报错信息

**Comment by chenchen0206** [comment]
![image](https://user-images.githubusercontent.com/55102972/128839309-882c48cf-f678-4dd4-a94b-032d17a18236.png)
![image](https://user-images.githubusercontent.com/55102972/128839324-851ddc22-d45c-4d96-b9a3-235fd348dc5a.png)
![image](https://user-images.githubusercontent.com/55102972/128839340-3809633a-6fb6-4ff2-9bff-1285e90a0799.png)

**Comment by chenchen0206** [comment]
在安卓上面是正常使用的

**Comment by gdwenjun** [comment]
https://pub.flutter-io.cn/packages/tencent_trtc_cloud/changelog
1.1.9 :
修复ios、macos截图失败的问题&其他问题。

**Comment by gdwenjun** [comment]
https://pub.flutter-io.cn/packages/tencent_trtc_cloud/changelog
1.1.9 :
修复ios、macos截图失败的问题&其他问题。
