### ISSUE TITLE
stopRemoteView 之后，再次startRemoteView 无效果

### ISSUE THREAD

**Issue by lan2000** [c1avie/TRTCSimpleDemo#24]
stopRemoteView 之后，再次startRemoteView 无效果，画面任然停留在最后一帧

tencent_trtc_cloud 1.1.7

`[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.630], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] Connected device (7 available)
    ! Device 127.0.0.1:5555 is offline.

• No issues found!
`

**Comment by lan2000** [comment]
查看tencent_trtc_cloud 更新日志，  _1.1.0 # 修复安卓stopRemoteView,再startRemoteView视频无法渲染问题_
然后特地使用1.1.0版本，stopRemoteView,再startRemoteView视频还是无法渲染

手机荣耀v10 安卓10

**Comment by c1avie** [comment]
这里我们安卓上线了updateRemoteView,可以尝试一下
