### ISSUE TITLE
fluttr应用安卓端怎么设置横屏模式

### ISSUE THREAD

**Issue by kenpz** [c1avie/TRTCSimpleDemo#25]
我的应用是横屏模式的，集成TRTC后视频通话是竖屏的，本地View旋转90度可以正常显示，但是远端web看到的是被旋转的view，设置远端用户旋转也无效
renderParams.rotation = TRTCCloudDef.TRTC_VIDEO_ROTATION_270;
    trtcCloud!.setRemoteRenderParams(
        userId, TRTCCloudDef.TRTC_VIDEO_STREAM_TYPE_BIG, renderParams);

**Comment by c1avie** [comment]
接口：https://pub.dev/documentation/tencent_trtc_cloud/latest/trtc_cloud/TRTCCloud/setVideoEncoderParam.html
https://pub.dev/documentation/tencent_trtc_cloud/latest/trtc_cloud_def/TRTCVideoEncParam/videoResolutionMode.html
