### ISSUE TITLE
TXAudioEffectManager.startPlayMusic 在IOS上無法播放protocol為"https"的來源

### ISSUE THREAD

**Issue by rest950** [c1avie/TRTCSimpleDemo#26]
android原生那段播放沒問題, iOS原生播放在ffmpeg似乎需要開啟一些設定

”https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.“

[I][audio_3a_processor_adsp.cpp, Print3aLevelApplyingLog, 301]:AudioEngine:Device enable adsp AEC to level 100
https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
[E][audio_ffmpeg.cpp, Open, 180]:AudioEngine : AudioFFmpeg Open failed, avformat_open_input file https://cdn.pixabay.com/download/audio/2021/07/27/audio_202082aa0b.mp3?filename=in-the-forest-ambient-acoustic-guitar-instrumental-background-music-for-videos-5718.mp3: -1330794744(Protocol not found)
[I][audio_ffmpeg.cpp, Release, 120]:AudioEngine : AudioFFmpeg Release begin
[I][audio_ffmpeg.cpp, Release, 139]:AudioEngine : AudioFFmpeg Release end

**Comment by gdwenjun** [comment]
这个历史比较久远，正在排期修复。可以先下载文件到本地后再设置startPlayMusic。
