### ISSUE TITLE
插件扩展建议: flutter tencent_trtc_cloud plugin

### ISSUE THREAD

**Issue by JiangJuHong** [c1avie/TRTCSimpleDemo#27]
插件扩展建议: flutter `tencent_trtc_cloud` plugin

建议将：`getDeviceManager`、`getBeautyManager`、指定明确返回值，否则使用以下写法时IDE将不存在提示：
````
_trctCloud.getDeviceManager().setAudioRoute(TRTCCloudDef.TRTC_AUDIO_ROUTE_SPEAKER);
````
源码处:
![image](https://user-images.githubusercontent.com/17740963/130835507-5151244f-0966-4fb2-b6d2-7d9d0274aedb.png)

使用不友好提示:
![image](https://user-images.githubusercontent.com/17740963/130835319-9b645515-8353-494a-90d2-3b8b88b866bd.png)

**Comment by c1avie** [comment]
收到，现在确实不友好，我们优化一下

**Comment by c1avie** [comment]
最新版本已更新
