### ISSUE TITLE
Please, update TXLiteAVSDK_ReplayKitExt SDK version to lasted version

### ISSUE THREAD

**Issue by ihdream72** [c1avie/TRTCSimpleDemo#29]
Hi 
I am testing screen sharing on iPhone with TRTCSimpleDemo ( v1.1.9 )

But it’s not working 

I received error message by “TXReplayKitExtReason.versionMismatch”.
So I had checked Tencent TRTC SDK versions. 
it's different version.

 - TXLiteAVSDK_ReplayKitExt : 8.1.9719
 - TXLiteAVSDK_TRTC : 8.8.10256
 
I think the SDK version is causing the problem
Please, update TXLiteAVSDK_ReplayKitExt SDK version to 8.8.10256.

**Comment by gdwenjun** [comment]
had update TXLiteAVSDK_ReplayKitExt  version
