### ISSUE TITLE
TXLiteAVSDK_ReplayKitExt   是不支持ios15么

### ISSUE THREAD

**Issue by supermebing** [c1avie/TRTCSimpleDemo#30]
Ld /Users/zilueit/Library/Developer/Xcode/DerivedData/Runner-dgdyskeemrfscebmoxxbiesjrneb/Build/Products/Debug-iphoneos/trtc.appex/trtc normal (in target 'trtc' from project 'Runner')
    cd /Users/zilueit/workspace/psp/yxtAppNew/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios15.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk -L/Users/zilueit/Library/Developer/Xcode/DerivedData/Runner-dgdyskeemrfscebmoxxbiesjrneb/Build/Products/Debug-iphoneos -F/Users/zilueit/Library/Developer/Xcode/DerivedData/Runner-dgdyskeemrfscebmoxxbiesjrneb/Build/Products/Debug-iphoneos -F/Users/zilueit/workspace/psp/yxtAppNew/ios -filelist /Users/zilueit/Library/Developer/Xcode/DerivedData/Runner-dgdyskeemrfscebmoxxbiesjrneb/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/trtc.build/Objects-normal/arm64/trtc.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../../Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/zilueit/Library/Developer/Xcode/DerivedData/Runner-dgdyskeemrfscebmoxxbiesjrneb/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/trtc.build/Objects-normal/arm64/trtc_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode-marker -fapplication-extension -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/zilueit/Library/Developer/Xcode/DerivedData/Runner-dgdyskeemrfscebmoxxbiesjrneb/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/trtc.build/Objects-normal/arm64/trtc.swiftmodule -e _NSExtensionMain -framework TXLiteAVSDK_ReplayKitExt -framework ReplayKit -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/zilueit/Library/Developer/Xcode/DerivedData/Runner-dgdyskeemrfscebmoxxbiesjrneb/Build/Intermediates.noindex/Runner.build/Debug-iphoneos/trtc.build/Objects-normal/arm64/trtc_dependency_info.dat -o /Users/zilueit/Library/Developer/Xcode/DerivedData/Runner-dgdyskeemrfscebmoxxbiesjrneb/Build/Products/Debug-iphoneos/trtc.appex/trtc

Undefined symbols for architecture arm64:
  "_vImageRotate90_Planar16U", referenced from:
      -[TXCReplayKitExtVideoEncoder newRotateCVPixelBuffer:rotation:] in TXLiteAVSDK_ReplayKitExt(TXCReplayKitExtVideoEncoder.o)
  "_vImageRotate90_Planar8", referenced from:
      -[TXCReplayKitExtVideoEncoder newRotateCVPixelBuffer:rotation:] in TXLiteAVSDK_ReplayKitExt(TXCReplayKitExtVideoEncoder.o)
  "___gxx_personality_v0", referenced from:
      -[TXCMediaStreamIPCTunnelClient init] in TXLiteAVSDK_ReplayKitExt(TXCMediaStreamIPCTunnelClient.o)
      -[TXCMediaStreamIPCTunnelClient initWithAsyncSocket] in TXLiteAVSDK_ReplayKitExt(TXCMediaStreamIPCTunnelClient.o)
      -[TXCMediaStreamIPCTunnelClient connectSocket] in TXLiteAVSDK_ReplayKitExt(TXCMediaStreamIPCTunnelClient.o)
      -[TXCMediaStreamIPCTunnelClient disconnect] in TXLiteAVSDK_ReplayKitExt(TXCMediaStreamIPCTunnelClient.o)
      -[TXCMediaStreamIPCTunnelClient connected] in TXLiteAVSDK_ReplayKitExt(TXCMediaStreamIPCTunnelClient.o)
      -[TXCMediaStreamIPCTunnelClient connectWithURL:] in TXLiteAVSDK_ReplayKitExt(TXCMediaStreamIPCTunnelClient.o)
      -[TXCMediaStreamIPCTunnelClient connectWithPort:] in TXLiteAVSDK_ReplayKitExt(TXCMediaStreamIPCTunnelClient.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by c1avie** [comment]
iOS 15支持，issue这里报错应该是少了依赖库，Accelerate.framework和libresolv.tb都加一下
