### ISSUE TITLE
Flutter Mac/Windows 不支持语音通话？？

### ISSUE THREAD

**Issue by lianyagang** [c1avie/TRTCSimpleDemo#31]
【Flutter Mac】-【0.0.0】Unhandled Exception: MissingPluginException(No implementation found for method initSDK on channel tencent_im_sdk_plugin)

【当前现象】：集成tencent_im_sdk_plugin，无法正常登录

**Comment by c1avie** [comment]
tencent_im_sdk_plugin，是IM的功能，MAC、widows在开发中。TRTC目前Mac/Windows是支持语音通话的。

**Comment by c1avie** [comment]
enterRoom之后就可以在房间里通话了

**Comment by lianyagang** [comment]
> enterRoom之后就可以在房间里通话了

整套的流程还需要登录im。但是，你们的imsdk，没有flutter版本的吧？

**Comment by c1avie** [comment]
imsdk还在开发中
