### ISSUE TITLE
Android 端 updateLocalView 似乎无效

### ISSUE THREAD

**Issue by JiangJuHong** [c1avie/TRTCSimpleDemo#33]
版本：tencent_trtc_cloud 1.2.7 
描述：查看 flutter tencent_trtc_cloud 插件 Changelog，发现1.2.3已支持android端进行`updateLocalView`和`updateRemoteView`。经测试，在1.2.7版本中不生效。同样的代码在ios设备上运行能够预期的进行`updateLocalView`、`updateRemoteView`，Android无任何效果。

**Comment by c1avie** [comment]
我们排查一下，有结论了同步

**Comment by c1avie** [comment]
已修复了此问题，请更新sdk版本到1.2.8，并把TRTCCloudVideoView的viewType指定为TRTCCloudDef.TRTC_VideoView_TextureView才有效

**Comment by JiangJuHong** [comment]
收到
